#https://seunggi92.tistory.com/196


SELECT R.ID, N.FISH_NAME AS FISH_NAME, R.LENGTH
FROM(    
SELECT ID, A.FISH_TYPE AS FISH_TYPE, A.LENGTH AS LENGTH
FROM FISH_INFO AS A, 
(SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE
) AS B
WHERE A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH
) AS R
JOIN FISH_NAME_INFO AS N
ON R.FISH_TYPE = N.FISH_TYPE
ORDER BY R.ID