# https://seunggi92.tistory.com/188

with recursive ANIMAL_OUTS_PEAK_TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM ANIMAL_OUTS_PEAK_TIME
    WHERE HOUR < 23
)

SELECT 
    ANIMAL_OUTS_PEAK_TIME.HOUR,
    COUNT(HOUR(A.DATETIME))
FROM ANIMAL_OUTS_PEAK_TIME
left join ANIMAL_OUTS as A
on ANIMAL_OUTS_PEAK_TIME.HOUR = HOUR(A.DATETIME)
GROUP BY ANIMAL_OUTS_PEAK_TIME.HOUR